#!/bin/bash
# Pre-commit hook installation script
# This script installs git hooks for automated quality checks

set -e

echo "Installing pre-commit hooks..."

# Create .git/hooks directory if it doesn't exist
mkdir -p .git/hooks

# Create pre-commit hook
cat > .git/hooks/pre-commit << 'EOF'
#!/bin/bash
# Pre-commit hook for automated quality checks
# Auto-generated by scripts/install-hooks.sh

set -e

echo "Running pre-commit checks..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check 1: Type checking
echo -e "${YELLOW}[1/3] Type checking...${NC}"
if command -v <type-check-command> &> /dev/null; then
    if <type-check-command>; then
        echo -e "${GREEN}✓ Type checking passed${NC}"
    else
        echo -e "${RED}✗ Type checking failed${NC}"
        echo -e "${RED}Fix type errors before committing${NC}"
        exit 1
    fi
else
    echo -e "${YELLOW}⚠ Type checker not found, skipping${NC}"
fi

# Check 2: Unit tests
echo -e "${YELLOW}[2/3] Running tests...${NC}"
if command -v <test-command> &> /dev/null; then
    if <test-command>; then
        echo -e "${GREEN}✓ All tests passed${NC}"
    else
        echo -e "${RED}✗ Tests failed${NC}"
        echo -e "${RED}Fix failing tests before committing${NC}"
        exit 1
    fi
else
    echo -e "${YELLOW}⚠ Test command not found, skipping${NC}"
fi

# Check 3: Common pitfalls (optional checks)
echo -e "${YELLOW}[3/3] Checking for common pitfalls...${NC}"

# Check for hardcoded magic numbers (warning only)
if git diff --cached --name-only | grep -E '\.(py|js|ts|cs|rs)$' > /dev/null; then
    MAGIC_NUMBERS=$(git diff --cached --diff-filter=d | grep -E '^\+.*[^0-9][2-9][0-9]+' | grep -v -E '(test_|spec_|CONSTANT|const |let |var )' || true)
    if [ -n "$MAGIC_NUMBERS" ]; then
        echo -e "${YELLOW}⚠ Warning: Possible magic numbers found:${NC}"
        echo "$MAGIC_NUMBERS" | head -5
        echo -e "${YELLOW}  Consider extracting these to named constants${NC}"
    fi
fi

# Check for non-deterministic operations (error)
if git diff --cached --diff-filter=d | grep -E '(Math\.random|random\.random|Date\.now)' > /dev/null; then
    echo -e "${RED}✗ Non-deterministic operations found (Math.random, random.random, Date.now)${NC}"
    echo -e "${RED}  Use seeded RNG instead (game.rng)${NC}"
    echo -e "${YELLOW}  To commit anyway: git commit --no-verify${NC}"
    exit 1
fi

# Check for layer violations (error)
if git diff --cached --diff-filter=d core/ 2>/dev/null | grep -E '(from presentation|import.*presentation|from application|import.*application)' > /dev/null; then
    echo -e "${RED}✗ Layer violation detected: Core importing Presentation or Application${NC}"
    echo -e "${RED}  Dependencies must flow: Presentation → Application → Core${NC}"
    exit 1
fi

echo -e "${GREEN}✓ All pre-commit checks passed!${NC}"
echo ""
echo "Proceeding with commit..."
EOF

# Make hook executable
chmod +x .git/hooks/pre-commit

echo "✓ Pre-commit hook installed successfully!"
echo ""
echo "The hook will automatically run:"
echo "  1. Type checking"
echo "  2. Unit tests"
echo "  3. Common pitfall checks"
echo ""
echo "To bypass the hook (not recommended):"
echo "  git commit --no-verify"
echo ""
echo "To update commands, edit .git/hooks/pre-commit"
echo "  - Replace <type-check-command> with your type checker"
echo "  - Replace <test-command> with your test runner"
